### ISSUE TITLE
F strings raising a Syntax Error

### ISSUE THREAD

**Issue by dtomlinson91** [badarsebard/pyden-suite#4]
Splunk version is 7.3.0
Splunk python is 2.7.15
Pyden python is 3.7.4

Running the following script (test.py):

```
import activate_default
import sys
import pandas
import base64

print("printing test env python3")

message = f'python version: {sys.version}'

print(message)

print('python version {}'.format(sys.version))
```

With the command `/opt/splunk/bin/python test.py`

Is giving the following error:

```
  File "test.py", line 10
    message = f'python version: {sys.version}'
                                             ^
SyntaxError: invalid syntax
```

If I comment out the f-string I get:

```
printing test env python3
python version 3.7.4 (default, Oct 30 2019, 02:51:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

as expected from using format().

As far as python3 functionality goes, it throws an error when using `print 'string'` as opposed to `print(string)`, so I know it's called the binary correctly, it's only f-strings that are giving this error.

**Comment by badarsebard** [comment]
So this an interesting one. The way the PyDen app works is by executing a script (activate.py) that uses the os module to restart the process under a different interpreter. So the script is initially started by the Splunk Python interpreter and then restarted using the PyDen interpreter. 

Even though Python is an interpreted language, there is still a compile process. The results are the pyc files you see by the same name of the py files that have been run in the past. The file is compiled by the interpreter and will throw the SyntaxError above if the script is malformed.  Since this occurs prior to run time, it is being performed by the Splunk Python interpreter which cannot recognize f-strings.

There is one definite workaround and one possible one. First option, use a Python 2 compatible print statement. This will definitely work. Option 2 is to use Splunk version 8 and set the script to use the Splunk Python 3 interpreter.

**Comment by dtomlinson91** [comment]
It confused me at first because trying a python2 print statement `print 'my string'` will fail because it is python 3, but using an fstring fails.

With what you've said am I correct that when the interpreter compiles the file that fstrings are handled differently than other statements (print for example)? Which is why using a python2 print statement fails?

The workaround falling back to `format()` isn't a big deal, small price to pay for the convenience of this app. Thanks for looking into it.

**Comment by badarsebard** [comment]
I should have been a little more specific. You can use the Python 3 print function, albeit without f strings, but you'll need to include the statement from __future__ import print_function at the top of the file. This will need to go above the activation import per Python requirements around importing from _future_.
