### ISSUE TITLE
Persistent splunk process + pyden

### ISSUE THREAD

**Issue by owenBeresford** [badarsebard/pyden-suite#9]
Good afternoon,
I have some non-persistent scripts which normally live for 1s; creating a fresh network and DB connection each request.  These work correctly with Pyden
I also have some real REST API (extending PersistentServerConnectionApplication) aka "persistent process", which dont.  It starts the request and hangs forever.
I'm guessing forking/exec*() calls breaks the data flow back from the child python process to the Splunk handler. 

Do you have any ideas about a working solution for the second case?
As ever thanks for your work

**Comment by badarsebard** [comment]
Looked into the issue a little while ago. If I recall correctly, Splunk doesn't really _run_ the customer REST endpoint scripts. It loads them into it's own Python framework and then that code gets executed by the framework. This may make the current activation sequence either inert, or possibly, actively disruptive since we are process swapping.

I have some random thoughts on how to get around this, but nothing solid yet. This will require a lot of experimentation (probably). I'm currently working on a testing framework to speed up development. This will make the experiments less painful and slow than using vagrant as I have in the past.

**Comment by badarsebard** [comment]
Further review of the Splunk PersistentServerConnectionApplication object and its related classes have led me to believe it will not be possible to utilize PyDen environments in a custom REST endpoint directly. The handler that is created and referenced by the restmap.conf is loaded into a server object run by the Splunk interpreter. Once loaded, the server object detects the appropriate method, executes it, and then returns the results. This is why the handler files are simply modules with no __main__ entrance or any code outside of the class definition. Simply put, Splunk isn't running the handler script, it's importing the class and executing it's methods.

Since PyDen leverages a process swap in order to switch the Python interpreter being used by Splunk it effectively starts the script over under the new executable. But in the case of REST endpoints, this would be the full server object. Even if we could figure out a way to inject the activation code into the handler, the new interpreter would be unable to execute the server object since it doesn't have access to the Splunk-built modules.

I'd say your best bet in order to utilize non-standard modules within a REST endpoint would be one of the following:
1) create a custom command that will execute the code you need and then create a REST endpoint to forward the request into the command and return the results. Or, if you're able, simply use the existing search endpoints to do this.
2) Create a custom REST endpoint that takes in the request and sends it to a subprocess that calls a second script. Write the second script with the needed libraries and have it output to stdout to be read by the subprocess communicate() method.
